/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bmf;

import com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel;
import java.awt.GridLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Francisco Javier Rubio Ibañez
 */
public class Interfaz extends javax.swing.JFrame {

    public static final int DIM = 10;
    public static int[][] matrizTerreno = new int[DIM][DIM];
    public static JLabel[][] celdas = new JLabel[DIM][DIM];
    public static String personaje;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        try {
            dibujarTerreno();
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    public void dibujarTerreno() throws IOException {

        terreno.setLayout(new GridLayout(DIM, DIM));

        for (int fila = 0; fila < DIM; fila++) {
            for (int columna = 0; columna < DIM; columna++) {
                celdas[fila][columna] = new JLabel();
                terreno.add(celdas[fila][columna]);
                celdas[fila][columna].setBorder(BorderFactory.createLineBorder(java.awt.Color.BLACK));
                //celdas[fila][columna].setIcon(new ImageIcon(getClass().getResource("/Imagenes/Pirolo.png")));
                // celdas[fila][columna].setEnabled(false);                
                celdas[fila][columna].setBackground(java.awt.Color.WHITE);
                celdas[fila][columna].setOpaque(true);

            }

        }

        //celdas[2][2].setIcon(new ImageIcon(getClass().getResource("/Imagenes/muro.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personajes = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        momboR = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        piroloR = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        lucasR = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        porcentajeMontana = new javax.swing.JSlider();
        porcentajeAgua = new javax.swing.JSlider();
        porcentajeBarranco = new javax.swing.JSlider();
        porcentajeMuro = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        entrenar = new javax.swing.JButton();
        crear = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        terreno = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BMF");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Personajes"));
        jPanel1.setToolTipText("Personajes");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mombo.png"))); // NOI18N

        personajes.add(momboR);
        momboR.setSelected(true);
        momboR.setText("Mombo");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pirolo.png"))); // NOI18N

        personajes.add(piroloR);
        piroloR.setText("Pirolo");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Lucas.png"))); // NOI18N

        personajes.add(lucasR);
        lucasR.setText("Lucas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(momboR)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(piroloR)
                    .addComponent(lucasR))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(momboR)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(piroloR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lucasR)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Valores"));

        porcentajeMontana.setMajorTickSpacing(10);
        porcentajeMontana.setMaximum(80);
        porcentajeMontana.setMinorTickSpacing(10);
        porcentajeMontana.setPaintLabels(true);
        porcentajeMontana.setPaintTicks(true);
        porcentajeMontana.setValue(0);

        porcentajeAgua.setMajorTickSpacing(10);
        porcentajeAgua.setMaximum(80);
        porcentajeAgua.setPaintLabels(true);
        porcentajeAgua.setPaintTicks(true);
        porcentajeAgua.setValue(0);

        porcentajeBarranco.setMajorTickSpacing(10);
        porcentajeBarranco.setMaximum(80);
        porcentajeBarranco.setPaintLabels(true);
        porcentajeBarranco.setPaintTicks(true);
        porcentajeBarranco.setValue(0);

        porcentajeMuro.setMajorTickSpacing(10);
        porcentajeMuro.setMaximum(80);
        porcentajeMuro.setPaintLabels(true);
        porcentajeMuro.setPaintTicks(true);
        porcentajeMuro.setValue(0);

        jLabel4.setText("Montaña");

        jLabel5.setText("Agua");

        jLabel6.setText("Barranco");

        jLabel7.setText("Muro");

        entrenar.setText("Entrenar");
        entrenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrenarActionPerformed(evt);
            }
        });

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        jLabel8.setText("Iteraciones: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(porcentajeBarranco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(porcentajeAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(porcentajeMontana, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(porcentajeMuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(crear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(entrenar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(porcentajeMontana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(porcentajeAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(porcentajeBarranco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(porcentajeMuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(crear)
                .addGap(18, 18, 18)
                .addComponent(entrenar)
                .addContainerGap())
        );

        javax.swing.GroupLayout terrenoLayout = new javax.swing.GroupLayout(terreno);
        terreno.setLayout(terrenoLayout);
        terrenoLayout.setHorizontalGroup(
            terrenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );
        terrenoLayout.setVerticalGroup(
            terrenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(terreno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(terreno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     son 5
     agua -> 1    
     barranco -> 2
     montana -> 3
     muro -> 4
    
    
    casa-> 30
    agente-> 31
    
    
    
    
    
     */
    public void crearMatriz(int montana,int barranco,int agua,int muro) {
        int num;
        int contMontana=0,contBarranco=0,contAgua=0,contMuro=0;
        
        
        for (int i = 0; i < DIM; i++) {
            for (int j = 0; j < DIM; j++) {

                num = (int) (Math.random() * 7 + 0);
                
                if(num==1){
                   
                    
                    if(agua!=contAgua){
                        matrizTerreno[i][j]=num;
                        contAgua++;
                    }
                    else{
                        matrizTerreno[i][j]=0;
                    }
                    
                }
                else if(num==2){
                    
                    
                    if(contBarranco!=barranco){
                        matrizTerreno[i][j]=num;
                        contBarranco++;
                    }
                    else{
                        matrizTerreno[i][j]=0;
                    }
                    
                    
                }
                else if(num==3){
                    
                    if(contMontana!=montana){
                        matrizTerreno[i][j]=num;
                        contMontana++;
                    }
                    else{
                        matrizTerreno[i][j]=0;
                    }
                    
                    
                }
                else if(num==4){
                    
 
                    
                    if(contMuro!=muro){
                        matrizTerreno[i][j]=num;
                         contMuro++;
                    }
                    else{
                        matrizTerreno[i][j]=0;
                    }
                    
                    
                }
                else{
                    matrizTerreno[i][j]=0;
                }

                
                pintarMapa(i, j);
                //System.out.print(matrizTerreno[i][j] + " ");

            }
            //System.out.println();
        }
    }

    public void pintarMapa(int fila, int columna) {

        switch (matrizTerreno[fila][columna]) {
            
            case 0:
                celdas[fila][columna].setIcon(null);
                break;

            case 1:
                celdas[fila][columna].setIcon(new ImageIcon(getClass().getResource("/Imagenes/agua.png")));
                break;
            case 2:
                celdas[fila][columna].setIcon(new ImageIcon(getClass().getResource("/Imagenes/barranco.png")));
                break;
            case 3:
                celdas[fila][columna].setIcon(new ImageIcon(getClass().getResource("/Imagenes/montana.png")));
                break;
            case 4:
                celdas[fila][columna].setIcon(new ImageIcon(getClass().getResource("/Imagenes/muro.png")));
                break;


        }

    }


    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        // TODO add your handling code here:
        int montana=0,barranco=0,agua=0,muro=0;
        int fila,columna;
        int aux;
        
        /*
        Inicializamos todo
        */

        
        if(DIM==10){
            aux=3;
        }else{
            aux=9;
        }
        
        
        //50% de
        muro=(porcentajeMuro.getValue()/DIM);
        muro*=aux;
        barranco=(porcentajeBarranco.getValue()/DIM);
        barranco*=aux;
        montana=(porcentajeMontana.getValue()/DIM);
        montana*=aux;
                
        agua=(porcentajeAgua.getValue()/DIM);
        agua*=aux;
        
       
        fila=(int)(Math.random()*4 + 0);
        columna=(int)(Math.random()*5 + 0);
        

        
        
        
        limpiar();
        crearMatriz(montana,barranco,agua,muro);
        
        
        celdas[fila][columna].setIcon(new ImageIcon(getClass().getResource("/Imagenes/casa.png")));
        matrizTerreno[fila][columna]=30;
        
        
        if(lucasR.isSelected()){
            colocarLucas();
            
        }
        else if(momboR.isSelected()){
            colocarMombo();
        }
        else if(piroloR.isSelected()){
            
            colocarPirolo();
            
        }
         

    }//GEN-LAST:event_crearActionPerformed

    private void entrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrenarActionPerformed
        // TODO add your handling code here:
         
        Entrenamiento e= new Entrenamiento();
        
        e.entrenar();
        
        
    }//GEN-LAST:event_entrenarActionPerformed

    
    public void colocarPirolo(){
        int fila,columna;
        personaje="Pirolo";
        
        fila=(int)(Math.random()*DIM + 0);
        columna=(int)(Math.random()*DIM + 0);
       
        celdas[fila][columna].setIcon(new ImageIcon(getClass().getResource("/Imagenes/Pirolo.png")));
        matrizTerreno[fila][columna]=31;
        
        
        
    }
    
    public void colocarLucas(){
       int fila,columna;
       personaje="Lucas";
        fila=(int)(Math.random()*DIM + 0);
        columna=(int)(Math.random()*DIM + 0);
        
        celdas[fila][columna].setIcon(new ImageIcon(getClass().getResource("/Imagenes/Lucas.png")));
        matrizTerreno[fila][columna]=31;
        
    }
    
    public void colocarMombo(){
         int fila,columna;
        personaje="Mombo";
        
        fila=(int)(Math.random()*DIM + 0);
        columna=(int)(Math.random()*DIM + 0);
        
        
        celdas[fila][columna].setIcon(new ImageIcon(getClass().getResource("/Imagenes/Mombo.png")));
        matrizTerreno[fila][columna]=31;
    }
    
    
    
    public void limpiar(){
        
        for(int i=0; i<DIM; i++){
            for(int j=0; j<DIM; j++){
                
                matrizTerreno[i][j]=0;
                pintarMapa(i, j);
            }     
        }
        
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new WindowsClassicLookAndFeel());
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
                }
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crear;
    private javax.swing.JButton entrenar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton lucasR;
    private javax.swing.JRadioButton momboR;
    private javax.swing.ButtonGroup personajes;
    private javax.swing.JRadioButton piroloR;
    private javax.swing.JSlider porcentajeAgua;
    private javax.swing.JSlider porcentajeBarranco;
    private javax.swing.JSlider porcentajeMontana;
    private javax.swing.JSlider porcentajeMuro;
    private javax.swing.JPanel terreno;
    // End of variables declaration//GEN-END:variables
}
